---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: perdana-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora-dx-nvidia-open
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    repos:
      cleanup: true
      files:
        - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
    #keys:
     # - https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
    install:
      skip-unavailable: true # skip unavailable packages
      packages:
        - repo: brave-browser
          packages: 
            - brave-browser
        
  #- type: default-flatpaks
   # configurations:
    #  - notify: true # Send notification after install/uninstall is finished (true/false)
     #   scope: system
        # If no repo information is specified, Flathub will be used by default
      #  install: # system flatpaks we want all users to have and not remove
       #   - org.mozilla.firefox
          
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
